language: ruby
script: "bundle exec rake spec"
rvm:
  - 2.3.1
env:
  - CODECLIMATE_REPO_TOKEN=891d362268d07d6ff0f5534f92252b6195f6be8795054d3627643eb6314a8c9e
gemfile:
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_40.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
notifications:
  email: false
matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/rails_32.gemfile
addons:
  code_climate:
    repo_token: 891d362268d07d6ff0f5534f92252b6195f6be8795054d3627643eb6314a8c9e
