language: ruby
script: "bundle exec rake spec"
rvm:
  - 2.6.4
env:
  - CODECLIMATE_REPO_TOKEN=891d362268d07d6ff0f5534f92252b6195f6be8795054d3627643eb6314a8c9e
gemfile:
  - gemfiles/rails_50.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
notifications:
  email: false
addons:
  code_climate:
    repo_token: 891d362268d07d6ff0f5534f92252b6195f6be8795054d3627643eb6314a8c9e
